language: node_js
branches:
  only:
  - master
node_js:
- node
before_script:
  - tar xzvf secrets.tar
  - npm install node-gyp -g && npm install bcrypt -g
script: npm test
before_install:
- openssl aes-256-cbc -K $encrypted_15d4b2a35eaf_key -iv $encrypted_15d4b2a35eaf_iv
  -in secrets.tar.enc -out secrets.tar -d
